scripts:
  gcs_bucket_name: solutions-public-assets

images:
  tproxy_registry: docker.io/danisla
  pullPolicy: IfNotPresent
  mitmproxy: mitmproxy/mitmproxy:2.0.2
  tproxy_initializer: tproxy-initializer:0.1.0
  tproxy_podwatch: tproxy-podwatch:0.1.0
  tproxy_sidecar: tproxy-sidecar:0.1.0

tproxy:
  useRBAC: false
  useInitializer: false
  hostPort: 8080
  addStandardModeProxy: false
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi