apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tproxy-test.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tproxy-test.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}