apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  mitm-script.py: |
    from mitmproxy import http
    import re
    import os

    ALLOW_BUCKET_NAME = "{{ .Values.scripts.gcs_bucket_name }}"

    RE_BUCKET = re.compile(r'https://storage.googleapis.com/%s/.*' % ALLOW_BUCKET_NAME)

    def request(flow: http.HTTPFlow) -> None:
        if not RE_BUCKET.match(flow.request.pretty_url):
            flow.response = http.HTTPResponse.make(
                418,
                b"Access Denied by Administrator",
                {"Content-Type": "text/html"}
            )