{{- if .Values.tproxy.useInitializer }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-initializer-config
  namespace: kube-system
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config: |
    containers:
      - name: tproxy
        image: {{ .Values.images.tproxy_registry }}/{{ .Values.images.tproxy_sidecar }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        securityContext:
          privileged: true
        env:
{{- if .Values.tproxy.blockSvcCIDR }}
          - name: BLOCK_SVC_CIDR
            value: "{{ .Values.tproxy.blockSvcCIDR }}"
{{- end }}
{{- if .Values.tproxy.allowDNS }}
          - name: ALLOW_DNS
            value: "{{ .Values.tproxy.allowDNS }}"
{{- end }}
{{- if .Values.tproxy.addStandardModeProxy }}
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
{{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
    volumes:
      - name: ca-certs-fedora
        configMap:
            name: {{ template "fullname" . }}-root-certs
            items:
              - key: root-certs.crt
                path: ca-bundle.crt
      - name: ca-certs-debian
        configMap:
            name: {{ template "fullname" . }}-root-certs
            items:
              - key: root-certs.crt
                path: ca-certificates.crt
    volumeMounts:
      - name: ca-certs-fedora
        mountPath: /etc/pki/tls/certs/
      - name: ca-certs-debian
        mountPath: /etc/ssl/certs/
      - name: ca-certs-debian
        # Adding the cert to the /extra dir preserves it if update-ca-certificates is run after init.
        mountPath: /usr/local/share/ca-certificates/extra/
    envVars:
{{- if .Values.tproxy.addStandardModeProxy }}
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: http_proxy
        value: $(HOST_IP):1080
      - name: https_proxy
        value: $(HOST_IP):1080
{{- end }}
{{- end }}