apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-initializer-config
data:
  config: |
    containers:
      - name: tproxy
        image: {{ .Values.images.tproxy_sidecar }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
    volumes:
      - name: ca-certs-fedora
        configMap:
            name: root-certs
            items:
              - key: root-certs.crt
                path: ca-bundle.crt
      - name: ca-certs-debian
        configMap:
            name: root-certs
            items:
              - key: root-certs.crt
                path: ca-certificates.crt
    volumeMounts:
      - name: ca-certs-fedora
        mountPath: /etc/pki/tls/certs/
      - name: ca-certs-debian
        mountPath: /etc/ssl/certs/
      - name: ca-certs-debian
        # Adding the cert to the /extra dir preserves it if update-ca-certificates is run after init.
        mountPath: /usr/local/share/ca-certificates/extra/
    envVars:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: http_proxy
        value: $(HOST_IP):1080
      - name: https_proxy
        value: $(HOST_IP):1080