apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-initializer
  initializers:
    pending: []
  labels:
    app: {{ template "fullname" . }}
    component: tproxy-initializer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: tproxy-initializer
      name: tproxy-initializer
    spec:
      containers:
        - name: tproxy-initializer
          image: {{ .Values.images.tproxy_initializer }}
          imagePullPolicy: Always
          args:
            - "-annotation=initializer.kubernetes.io/tproxy"
            - "-require-annotation=true"
            - "-namespace={{ .Release.Namespace }}"
            - "-configmap={{ template "fullname" . }}-initializer-config"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi