{{- if .Values.tproxy.useInitializer }}
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
initializers:
  - name: tproxy.initializer.kubernetes.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deployments
{{- end }}