## After deploying, run this:
# pod=$(kubectl get pod --selector=run=tproxy-podwatch -o jsonpath='{.items..metadata.name}')
# kubectl exec -it ${pod} -- mkdir -p /go/src/github.com/danisla/tproxy-podwatch/
# kubectl cp main.go ${pod}:/go/src/github.com/danisla/tproxy-podwatch/main.go
# kubectl exec -it ${pod} -- sh -c 'cd /go/src/github.com/danisla/tproxy-podwatch/ && go get ./...'

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tproxy-podwatch
  labels:
    run: tproxy-podwatch
spec:
  selector:
    matchLabels:
      run: tproxy-podwatch
  template:
    metadata:
      labels:
        run: tproxy-podwatch
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 10
      containers:
        - name: tproxy-podwatch
          image: 'golang:1.8'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - bash
            - '-c'
            - "(apt-get update && apt-get install -y iptables && echo 'INFO: Waiting for pod termination.') && (while true; do sleep 1000; done) & child=$! && wait $child"