{{- if .Values.tproxy.useInitializer }}
{{- if .Values.tproxy.useRBAC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tproxy.fullname" . }}-initializer
  namespace: kube-system
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: initializer
---
# Grant the initializer access to watch deployments in all namespaces and access it's configmap.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "tproxy.fullname" . }}-initializer
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: initializer
subjects:
- kind: ServiceAccount
  name: {{ template "tproxy.fullname" . }}-initializer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ template "tproxy.fullname" . }}-initializer
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "tproxy.fullname" . }}-initializer
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: initializer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  resourceNames:
  - {{ template "tproxy.fullname" . }}-initializer
  verbs: ["get", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get","list", "watch"]
---
# Grant initializer access to update deployments in the release namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "tproxy.fullname" . }}-initializer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: initializer
subjects:
- kind: ServiceAccount
  name: {{ template "tproxy.fullname" . }}-initializer
  namespace: kube-system
roleRef:
  kind: Role
  name: {{ template "tproxy.fullname" . }}-initializer
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "tproxy.fullname" . }}-initializer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: initializer
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["*"]
{{- end }}
{{- end }}